kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: awsstorageclass
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  encrypted: "true"
