apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychainvalidator4ibft
  namespace: supplychain-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainvalidator4ibft
  chart:
    git: https://github.com/zandercreations/herbalcoin.git
    ref: main
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://a4e6e3932b0f485ff7099b3272b08345e4a4540e51e69289d85eb58ea24d8d19bca36f2639b1bca6d061aa63d5cb6f39a60a56e34a6a2531188b8cab8dcd651e@validator1.bc.myherbalway.com:15010"
      
      - "enode://bad768bc785452b425a0714b5950ff719e9f971291feae1ce1b822f1f32778cad80c8af50cea9cd3891284fa9040b40e7353072f10e55b1dd1399de06e894a04@validator2.bc.myherbalway.com:15012"
      
      - "enode://c2193c7f3c13fbe8cb904fdccba25a95e8a92b05a44c99b303f3f9b1ddd19680e45164c772407d07ac24c5efb1255cacb6a589648e1b9a932b77cba5a2455ef2@validator3.bc.myherbalway.com:15014"
      
      - "enode://ad73f0fa002061b200ed265c3ccd46a52b8b30c4597c18ac020661bb39f68d6cb6131c3eae902c50899522950203d35daf61a83cbc66eee0c71ef83845b6f812@validator4.bc.myherbalway.com:15016"
      

    metadata:
      namespace: supplychain-bes
      labels:

    ambassador:
      external_url_suffix: bc.myherbalway.com

    liveliness_check:
      enabled: false

    proxy:
      provider: ambassador
      external_url: supplychain.bc.myherbalway.com
      p2p: 15016
      rpc: 15017

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator4
      tls: False
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: https://bcv.syncoin.io/
      secretprefix: herbalway/data/supplychain-bes/crypto/validator4
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychain

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NGEwNmRmZTFjMGFmMjExYmRlZTQ1OGU3YWNjNGQ3MTNkYTVjNmFlYTg5NDRhODJhNGVjNjI2ZmMwMzI1ZjgwYmVjYzIwNWE1OTA0YjkyNTU4ZWU5NGMxMGZlYjk5Y2FiMGU0ODBlNGUwNDM2ZDFiYjQ2MmY0OTA0MzQ2ODA5NDY2OGE0OTZjNGFkYmI1NGI4MGQ3Zjc3MGI2Y2Q5ZjViMjQ4ZjdjM2I4MDg0MDAwMDAwMDBjMCIKfQ==
